export const siteConfig = {
  name: "Paolo Roncaglioni",
  title: "M.Sc. Computer Science Engineer · Solution Architect · ML Enthusiast",
  description: "Portfolio website of Paolo Roncaglioni",
  accentColor: "#1d4ed8",
  photo: "/avatar.jpg",
  resume: "/resume.pdf",
  social: {
    email: "paolo.roncaglioni@gmail.com",
    linkedin: "https://linkedin.com/in/paolo-roncaglioni",
    github: "https://github.com/roncax",
  },
  aboutMe:
    "I'm a highly motivated professional with a Master of Science in Computer Science Engineering, specializing in Machine Learning. As a Solution Architect at a prominent IT company, I thrive on designing innovative solutions that leverage cutting-edge technology to address complex business challenges. I constantly seek new developments in the field and stay updated with the latest trends. Beyond my professional endeavors, I'm a passionate rugby player — a sport that teaches me teamwork, resilience, and strategic thinking, qualities I bring to my professional life.",
  skills: [
    "Java",
    "Java Spring",
    "Python",
    "JavaScript",
    "Angular",
    "Kotlin",
    "Android",
    "C",
    "C++",
    "HTML",
    "CSS",
    "AWS Services",
    "Docker",
    "Kubernetes",
    "Apache Kafka",
    "Camunda",
    "SQL",
    "Git",
    "Terraform",
    "PyTorch",
    "FreeCad",
  ],
  projects: [],
  experience: [
    {
      company: "Accenture",
      title: "Enterprise Architect Consultant",
      dateRange: "06/2024 - Present",
      bullets: [
        "Software Architect and Team Lead for a multi-country global team (Germany, Greece, Spain, India) at a major insurance company, following Agile methodologies with a multi-microservices architecture on AWS using DevOps IaaC tools (Terraform, GitLab).",
        "Full-stack engineer (DevOps, Backend, Frontend) for an internal paper-to-web digitalization web service using Angular, Java Spring, and AWS services.",
      ],
    },
    {
      company: "Accenture",
      title: "Enterprise Architect Analyst",
      dateRange: "02/2022 - 05/2024",
      bullets: [
        "Software Developer for a multi-country global team at a major insurance company, working on a full microservices architecture with Agile methodologies.",
        "Lead developer for an internal image-to-text serverless OCR orchestrator (AWS Lambda, Step Functions) integrating Azure ML services.",
      ],
    },
    {
      company: "STMicroelectronics",
      title: "Software Design Intern",
      dateRange: "11/2021 - 02/2022",
      bullets: [
        "Python database management and data presentation for an internal project.",
      ],
    },
  ],
  education: [
    {
      school: "Politecnico di Milano",
      degree: "Master's Degree - Computer Science and Engineering",
      dateRange: "2021",
      achievements: [
        "Significant studies on software engineering and machine learning.",
        "Thesis: \"Ensemble methods for multi-organ semantic segmentation\" — semantic segmentation of organs in medical images with neural networks.",
        "Final grade: 100/110.",
      ],
    },
    {
      school: "Politecnico di Milano",
      degree: "Bachelor's Degree - Computer Science and Engineering",
      dateRange: "2018",
      achievements: [],
    },
  ],
};
